---
include:
  # Scanner - Non-Touch Mode (display only, no swipe navigation)
  - board: xiao_ble/nrf52840
    shield: prospector_scanner
    artifact-name: prospector_scanner

  # Scanner - Touch Mode (swipe navigation + settings screens)
  - board: xiao_ble/nrf52840
    shield: prospector_scanner
    cmake-args: -DEXTRA_CONF_FILE=../../config/prospector_scanner_touch.conf
    artifact-name: prospector_scanner_touch

  # Scanner - Dongle Mode (USB HID forwarding + display)
  - board: xiao_ble/nrf52840
    shield: prospector_scanner
    cmake-args: -DEXTRA_CONF_FILE=../../config/prospector_scanner_dongle.conf
    artifact-name: prospector_scanner_dongle

  # Scanner - Dongle + Touch Mode
  - board: xiao_ble/nrf52840
    shield: prospector_scanner
    cmake-args: -DEXTRA_CONF_FILE="../../config/prospector_scanner_touch.conf;../../config/prospector_scanner_dongle.conf"
    artifact-name: prospector_scanner_dongle_touch

  # Settings reset utility
  - board: xiao_ble/nrf52840
    shield: settings_reset
